TARGET   = libpak.bc
CLASSES  = pak_file pak_log
SOURCE   = $(CLASSES:%=%.c)
OBJECTS  = $(SOURCE:.c=.bc)
HFILES   = $(CLASSES:%=%.h)
FLAGS    = -O2 -Wall
EMCC     = emcc

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(EMCC) $(OBJECTS) $(FLAGS) -o $(TARGET)

clean:
	rm -f $(OBJECTS) *~ \#*\# $(TARGET)

%.bc: %.c $(HFILES)
	$(EMCC) $(FLAGS) $< -o $@
